name: CI having lint (flack8 + black) + test coverage
# run only when pushing to main or a PR to main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-with-black:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Lint Code Base with BLACK
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          # Change to 'master' if your main branch differs
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # default value for VALIDATE_PYTHON_FLAKE8 and VALIDATE_PYTHON_BLACK are true
          VALIDATE_PYTHON_FLAKE8: false

  lint-with-flake8:
    runs-on: ubuntu-latest
    needs: lint-with-black

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Lint Code Base with FLAKE8
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          # Change to 'master' if your main branch differs
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # default value for black and flake8 are true
          VALIDATE_PYTHON_BLACK: false

  unit-test:
    runs-on: ubuntu-latest
    needs: [lint-with-black, lint-with-flake8]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: run test and build coverage files
        run: |
          pytest --cov-report "xml:coverage.xml" --cov=.

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-xml-coverage-path: ./coverage.xml